spring.application.name=OpenAi

login.pattern.console=%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n

spring.ai.model.chat=openai
spring.ai.openai.base-url=http://localhost:12434/engines/v1
spring.ai.openai.chat.model=ai/gemma3:4b
spring.ai.openai.api-key=dummy

# Docker Model Runner doesn't provide embeddings
spring.ai.model.embedding=none

server.port=8082