spring.application.name=OpenAi
login.pattern.console = %green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n
spring.ai.model.chat=ollama
spring.ai.ollama.chat.model=llama3.2:latest
server.port=8082
